config/routes.rb
Rails.application.routes.draw do

  root "authors#index"

  resources :regions
  resources :publishers
  resources :publications
  resources :authors
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :author
  belongs_to :book
  belongs_to :publisher
  belongs_to :region
  has_many :regions
  delegate :name, to: :author, prefix: true
  delegate :title, to: :book, prefix: true
  delegate :name, to: :publisher, prefix: true
  delegate :name, to: :region, prefix: true
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]

  # GET /publications or /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1 or /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:date, :author_id, :book_id, :publisher_id, :region_id)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<div class="tile is-vertical box is-5">
  <div class="p-5">
    <h1 class="title"><%= action_controller_title %></h1>
    <%= form_with(model: publication) do |form| %>
      <% if publication.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

          <ul>
            <% publication.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :date, class:"label"  %>
        <%#= form.date_select :date, class: "select" %>
        <div class="select is-small mr-2">
          <%= form.date_select :date, {date_separator: "</div><div class='select is-small mr-2'>"} %>
        </div>
      </div>

      <div class="field">
        <%= form.label :region, class:"label" %>

        <div class="select is-small">
          <%= form.collection_select :region_id, Region.order(:region), :id, :name, {:include_blank => 'Select Region'} %>
        </div>
      </div>

      <!--<div class="field">-->
      <!--<%#= form.label :author_id %>-->
      <!--<%#= form.text_field :author_id %>-->
      <!--</div>-->
      <!--Added-->
      <div class="field">
        <%= form.label :author, class:"label" %>
        <div class="select is-small">
          <%= form.collection_select :author_id, Author.order(:name), :id, :name, {:include_blank => 'Select Author'} %>
        </div>
      </div>

      <!--<div class="field">-->
      <!--<%#= form.label :book_id %>-->
      <!--<%#= form.text_field :book_id %>-->
      <!--</div>-->
      <!--Added-->
      <div class="field">
        <%= form.label :book, class:"label" %>
        <div class="select is-small">
          <%= form.collection_select :book_id, Book.order(:title), :id, :title,{:include_blank => 'Select Book'} %>
        </div>
      </div>


      <!--<div class="field">-->
      <!--<%#= form.label :publisher_id %>-->
      <!--<%#= form.text_field :publisher_id %>-->
      <!--</div>-->

      <!--Added-->
      <div class="field">
        <%= form.label :publisher, class:"label" %>
        <div class="select is-small">
          <%= form.collection_select :publisher_id, Publisher.order(:name), :id, :name, {:include_blank => 'Select Publisher'} %>
        </div>
      </div>

      <!--<div class="actions control mt-5">-->
        <!--<%#= form.submit :submit, class: "button is-link is-primary is-align-content-end" %>-->
      <!--</div>-->
      <div class="actions control">
        <% if action_name == "new" %>
          <%= form.submit "Add #{controller_single_camel}", class:"button is-link is-primary" %>
        <% else %>
          <%= form.submit "Update", class:"button is-link is-primary" %>
        <% end %>
      </div>

    <% end %>
  </div>
</div>

app/views/publications/edit.html.erb
<%= render 'form', publication: @publication %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<p id="notice"><%= notice %></p>

<%= render "layouts/page/title_new_path" %>

<table class="table is-cell-bordered no-background">
  <thead>
    <tr>
      <th colspan="1">Date</th>
      <th colspan="1">Region</th>
      <th colspan="2">Author</th>
      <th colspan="2">Book</th>
      <th colspan="2">Publisher</th>
      <th colspan="3" rowspan="2" class="has-text-centered" >Actions</th>
    </tr>
    <tr>
      <th>Date</th>
      <th>Region</th>
      <th>ID</th>
      <th>Name</th>
      <th>ID</th>
      <th>Name</th>
      <th>ID</th>
      <th>Name</th>
    </tr>

  </thead>

  <tbody>
    <% @publications.each do |publication| %>
      <tr>
        <td><%= publication.date %></td>
        <td><%= publication.region_name %></td>
        <td><%= publication.author_id %></td>
        <td><%= publication.author_name %></td>
        <td><%= publication.book_id %></td>
        <td><%= publication.book_title %></td>
        <td><%= publication.publisher_id %></td>
        <td><%= publication.publisher_name %></td>
        <td><%= link_to 'Show', publication %></td>
        <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
        <td><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/publications/new.html.erb
<%#= render 'layouts/page/back' %>

<%= render 'form', publication: @publication %>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @publication.date %>
</p>

<p>
  <strong>Author:</strong>
  <%= @publication.author_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @publication.book_id %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @publication.publisher_id %>
</p>

<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %>