config/routes.rb
Rails.application.routes.draw do

  root "authors#index"

  resources :regions
  resources :publishers
  resources :publications
  resources :authors
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
  has_many :publications
  has_many :publishers, through: :publications
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<div class="tile box is-vertical is-4 ml-4 p-3">
  <div class="p-5">
    <h1 class="title"><%= action_controller_title %></h1>  
    <%= form_with(model: author, class:"form") do |form| %>
      <% if author.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

          <ul>
            <% author.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :name, class:"label" %>
        <div class="control">
          <%= form.text_field :name, class:"input is-small" %>
        </div>
      </div>

      <!--Possibly consider similare use for future, making forms more DRY-->
      <!--<%#= render "layouts/form_submit_name" %>-->
      
      <div class="actions control">
        <% if action_name == "new" %>
          <%= form.submit "Add #{controller_single_camel}", class:"button is-link is-primary" %>
        <% else %>
          <%= form.submit "Update", class:"button is-link is-primary" %>
        <% end %>
      </div>

    <% end %>
  </div>
</div>

app/views/authors/edit.html.erb
<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<div class="block">

  <p id="notice"><%= notice %></p>

<%= render "layouts/page/title_new_path" %>

  <table class="table is-cell-bordered no-background">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th colspan ="3" class="has-text-centered">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @authors.each do |author| %>
        <tr>
          <td><%= author.id %></td>
          <td><%= author.name %></td>
          <td><%= link_to 'Show', author %></td>
          <td><%= link_to 'Edit', edit_author_path(author) %></td>
          <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/authors/new.html.erb
<%= render 'form', author: @author %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<div class="content">
  <div class="title">
    <%= @author.name %>
  </div>
  <div class="block">
    <%= link_to 'Back', authors_path %> |
    <%= link_to 'Edit Author', edit_author_path(@author) %> 
  </div>

  <p>
  <strong>Books:</strong>
  </p>
  <ol type="1">
    <% @author.books.each do |book| %>
      <li><%= book.title %></li>
    <% end %>
  </ol>
</div>