config/routes.rb
Rails.application.routes.draw do

  root "authors#index"

  resources :regions
  resources :publishers
  resources :publications
  resources :authors
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :publications
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: %i[ show edit update destroy ]

  # GET /regions or /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1 or /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions or /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: "Region was successfully created." }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1 or /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: "Region was successfully updated." }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1 or /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: "Region was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def region_params
      params.require(:region).permit(:name)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.erb
<div class="tile box is-vertical is-5">
  <div class="p-5">
  <h1 class="title"><%= action_controller_title %></h1>  
  <%= form_with(model: region, class:"form") do |form| %>
    <% if region.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(region.errors.count, "error") %> prohibited this region from being saved:</h2>

        <ul>
          <% region.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name, class:"label" %>

      <div class="control">
        <%= form.text_field :name, class:"input is-small" %>
      </div>
    </div>

    <!--<div class="actions control is-flex-direction-row is-align-content-end is-align-content-space-around">-->
      <!--<%#= form.submit "Create #{controller_single_camel}", class: "button is-link is-primary is-small" %>-->
    <!--</div>-->
      <div class="actions control">
        <% if action_name == "new" %>
          <%= form.submit "Add #{controller_single_camel}", class:"button is-link is-primary" %>
        <% else %>
          <%= form.submit "Update", class:"button is-link is-primary" %>
        <% end %>
      </div>

  <% end %>
  </div>
</div>

app/views/regions/edit.html.erb
<%= render 'form', region: @region %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>

app/views/regions/index.html.erb
<p id="notice"><%= notice %></p>

<%= render "layouts/page/title_new_path" %>

<table class="table is-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.name %></td>
        <td><%= link_to 'Show', region %></td>
        <td><%= link_to 'Edit', edit_region_path(region) %></td>
        <td><%= link_to 'Destroy', region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/regions/new.html.erb
<%#= render 'layouts/page/back' %>

<%= render 'form', region: @region %>

app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @region.name %>
</p>

<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Back', regions_path %>