config/routes.rb
Rails.application.routes.draw do

  root "authors#index"

  resources :regions
  resources :publishers
  resources :publications
  resources :authors
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_form_submit_name.html.erb
<!--Currently cant be used because no known 'form' within this section to be inserted within the form_with (no reference)-->
<div class="actions control">
  <% if action_name == "new" %>
    <%= form.submit "Add #{controller_single_camel}", class:"button is-link is-primary" %>
  <% else %>
    <%= form.submit "Update", class:"button is-link is-primary" %>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Home
      </a>

      <a class="navbar-item">
        Documentation
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary">
            <strong>Sign up</strong>
          </a>
          <a class="button is-light">
            Log in
          </a>
        </div>
      </div>
    </div>

  </div>
</nav>

app/views/layouts/_tabs.html.erb
<div class="tabs has-text-primary is-boxed">
  <ul>
    <li class="<%= is_active?(:authors) %>" >
      <%= link_to "Authors", authors_path %>
    </li>
    <li class="<%= active_page?(:books) %>">
      <%= link_to "Books", books_path %>
    </li>
    <li class="<%= active_page?(:publishers) %>">
      <%= link_to "Publishers", publishers_path %>
    </li>
    <li class="<%= active_page?(:regions) %>">
      <%= link_to "Regions", regions_path %>
    </li>
    <li class="<%= active_page?(:publications) %>">
      <%= link_to "Publications", publications_path %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails004HasManyThrough</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav>
        <%#= render "layouts/nav" %>
        <%= render "layouts/tabs" %>
      </nav>
      <!--Render desired navigation section if main page is any of the following-->
      <% if controller_name.to_s.in?(["books","authors","regions","publishers","publications"])  %>
          <%= render "layouts/page/navigation" %>
      <% end %>
    </header>

    <section class="section">
      <%= yield %>
    </section>
    
    <footer>
    </footer>
  </body>
</html>